### ISSUE TITLE
Kodi 18.6

### ISSUE THREAD

**Issue by Vipale** [linuxserver/docker-kodi-headless#112]
Hey there,

have you figured out a new maintainter for this?
I thought hugepants would take over, but his pull request is there for 21 days now. 
It would really nice to be able to update to kodi 18.6.

**Comment by hugepants** [comment]
Hey,
I am the new maintainer. The current implementation is no longer suitable because it takes too long to build for all the architectures. So I won't be merging that PR.

I'm working on a different implementation which will work with the current LSIO pipeline.

In the meantime, you can continue to use 18.5 as most point releases don't impact headless functionality very much. Is there a specific fix in 18.6 that you need?

**Comment by Vipale** [comment]
Hey, 

great to hear!

I was just wondering if this is still alive or if should start looking for another docker implementation.

18.5 is fine for now, I was more worried about 19 and wanted to make sure I am using an maintained docker file ;)

**Comment by hugepants** [comment]
Yes, still alive, just with slower progress than expected due to the global crisis right now.

**Comment by Vipale** [comment]
Yeah, that hit us all.
Stay safe and healthy!
