### ISSUE TITLE
Kodi.bin segfaults

### ISSUE THREAD

**Issue by llonca13** [linuxserver/docker-kodi-headless#25]
![www](https://cloud.githubusercontent.com/assets/17835147/18418124/f6f8ae98-7840-11e6-9b41-fcd61c7a4c92.JPG)

heres my log from unraid..tell me how more i can help(with more logs or something).thanks

**Comment by aptalca** [comment]
It is a problem affecting all headless installs of kodi. Likely an issue on the kodi side. I believe members of the lsio team are aware and trying to figure out a fix along with kodi devs

**Comment by Kolbasz12** [comment]
any updates on this between lsio team and kodi devs?  Issue wouldnt be bad if things restarted efficiently, but there are times kodi is offline for hours.

**Comment by matthuisman** [comment]
disabling addon updates worked for me.
However, my segfaults anytime trying to view any TV shows or Movies via web interface.
I also get exact same fault if compile natively (I'm using Odroid XU4 armHF) or using a Ubuntu headless container.

Can anyone confirm if they can view the media via the web interface?

I thought possibly it's a LibCURL issue.
I noticed a little note at bottom of KODI Wiki
http://kodi.wiki/view/HOW-TO:Compile_Kodi_for_Debian_or_Ubuntu

NOTE: On certain versions of Ubuntu, you may get a segmentation fault due to libcurl. This is resolved by creating a symbolic link in /usr/lib

cd /usr/lib
sudo ln -s libcurl-gnutls.so.4 libcurl.so.4

I tried this on my native build, without any luck :(

**Comment by sparklyballs** [comment]
Bug label has been added for the Jarvis branch only, but it should be clear that the problem lies upstream and is affecting Jarvis based kodi headless containers from other authors, hence the wontfix label (there isn't a cantfix).
