### ISSUE TITLE
Library updates failing

### ISSUE THREAD

**Issue by nfugal** [linuxserver/docker-kodi-headless#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io
I have Kodi-headless setup in the following manner:
  + Host OS: Ubuntu 18.04
  + Docker create command:  `docker create --name=kodi-headless-nate -v /home/nfugal/Docker/kodi.nate/config/:/config/.kodi -e PGID=1000 -e PUID=1000 -e TZ=America/Denver -p 8080:8080 -p 9091:9091 -p 9777:9777/udp linuxserver/kodi-headless:Krypton`
  + Symlinks: none
  + Docker log output: 
```-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ERROR: Exception caught on main loop. Exiting
./run: line 2:   213 Segmentation fault      (core dumped) s6-setuidgid abc /usr/lib/kodi/kodi.bin --headless
Can't open display 
Can't open display
```
_____________________________________

I have Sonarr pointed to my headless-kodi. The connection test in Sonarr passes. I have it set to update the Kodi library when new media is added. When new media is added to Sonarr, the Kodi library doesn't get updated. I know the database, advancedsettings, & sources files are correct because they are copied from working clients. I can successfully update the Kodi library from other clients.

The media is all stored on SMB shares hosted on a FreeNAS box.

Any idea where the issue(s) with my setup might lie?

**Comment by nfugal** [comment]
Edits were all adjusting the formatting.

**Comment by HumorBaby** [comment]
Same issue :cry:

**Comment by HumorBaby** [comment]
Nevermind, I figured it out. For me it was a three part problem:

1. When using docker-compose, I was mounting a directory `config` containing a `.kodi` folder into `/config`
```
...
volumes:
  - "./config:/config"
...
```
Apparently, docker (or maybe just because of docker-compose, idk...) won't include the hidden directory (`./config/.kodi`; the `.kodi` part) in the mount (or maybe something more complicated was happening that I missed).

2. I needed to give write permission to the `PUID` specified into the `.kodi` folder so it could populate non-userdata files.

3. I also had a `advancedsettings.xml` file that did not have a webserver started, which sonarr needed, so even after I fixed 1 and 2, I needed to add these settings to my `advancedsettings.xml`; normally the default `advancedsettings.xml` would enable this.

Maybe pts 1 and 2 might help you @nfugal
