### ISSUE TITLE
Heavy CPU load kodi-x11

### ISSUE THREAD

**Issue by sinopsysHK** [linuxserver/docker-kodi-headless#87]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Linux 3.10.105 #23824 SMP Fri Sep 7 12:50:13 CST 2018 x86_64 GNU/Linux synology_x86_411+II

Latest image:
`linuxserver/kodi-headless      Leia                6d39b0532410        2 days ago`

Script to create the container:
`docker create --name=kodi-server \
-v /volume1/docker/kodi/cfg:/config/.kodi \
-e PGID=100 -e PUID=1024 \
-e TZ="Asia/Hong_Kong" \
-p 8087:8080 \
-p 9090:9090 \
-p 9777:9777/udp \
linuxserver/kodi-headless:Leia`

Docker logs:
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

I'm using a volume mount that is the same as the one used with prior version (17) and was working very well

Once startup up is finalized with all the scans done, I still have a heavy CPU load with kodi-x11 process:
PID USER      PR  NI    VIRT    RES  **%CPU** %MEM     TIME+ S COMMAND                                                                         
11276 admin     20   0 2806.3m 436.4m **265.2** 11.0  15:44.39 S /usr/lib/x86_64-linux-gnu/kodi/kodi-x11 --standalone --debug

While nothing is showing in debug log assuming it isn't performing any tasks !?

Beside I have Xorg looping in an endless error loop:
`[658907.152] (EE) dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory)`
... raised every ~10s

I do not understand why do Xorg has to run on an headless server ?
Same for pulseaudio: is that mandatory ?

**Comment by sparklyballs** [comment]
there's no headless patch for Leia, and i don't know if there's going to be one available anytime soon , if ever in fact.
currently the only way to run it is via xpra , and yeah it hits the cpu damn hard when scanning....

**Comment by sinopsysHK** [comment]
If ever it was only while scanning :(
In my case it is hitting hard even idling or there are some shadow tasks with no logs running behind the scene but as per logs all workers ended.

It can’t be the jsonrpc or chorus web server listening actively !?

**Comment by Celedhrim** [comment]
Hi @sinopsysHK 

Long time I have maintain the headless patch , but because build time take longer and longer on docker hub , I have stop this and switch to xpra with the overhead of ram and cpu because interface is now fully render.
Just before leia release when I see that I can't build as fast as needed I've consider switch to linuxserver.io image. Then I see they just take my work ( and donations ... ).
So I've start trying another way with fake X server (xpra) and soundcard (pulseaudio).

 that's why they no more provide headless patch and now provide xpra images.

https://github.com/Celedhrim/docker-kodi-server

**Comment by CHBMB** [comment]
@sparklyballs Is the man to talk to about this @Celedhrim the rest of us don't get involved in Kodi Headless and use Emby as a backend to Kodi

**Comment by Celedhrim** [comment]
It's ok , I do it for myself and share with other if it's useful for them, but you can just tell your source.
( and maybe don't take donation for that )

**Comment by CHBMB** [comment]
One thing I will say is @sparklyballs has been involved in the Kodi Headless thing for a long time.   So I'm not sure what your username on the Kodi forums is but here's a thread going back to 2014 and Sparkly was the second one to post.

https://forum.kodi.tv/showthread.php?tid=212061

And your own docker container is a fork of someone elses.  So I'm not sure I fully agree with your donations comment but whatever.....

This container was one that @sparklyballs bought with him to LS.io when he joined and goes back a long way to the Helix days, turns out you both forked the same container and looks like Sparkly rewrote it with Unraid in mind.

**Comment by Celedhrim** [comment]
Their was a thread before that (https://forum.kodi.tv/showthread.php?tid=132919)

I was first make pull request to werner repo then he stop working on xbmc-headless.
That's why I fork , to continue maintaining that.

You can see werner and I job before sparky fork.

https://github.com/sparklyballs/docker-xbmc-server/commits/master

But nevermind , I don't care this.

I just explain why there is no more headless patch for kodi and from where it's come from.

**Comment by CHBMB** [comment]
@Celedhrim I'm sorry if this has caused any offence, certainly never been our intention, sorry I can't be more informative about things.

**Comment by sparklyballs** [comment]
@Celedhrim 

There is an acknowledgement of sorts for patches etc coming from the kodi community...

https://github.com/linuxserver/docker-kodi-headless#credits

**Comment by sparklyballs** [comment]
also, several occasions for point releases of earlier versions, the patch has been modified by ourselves when things have changed.
but then again, the original patch was made by topfs2 (sp) and everything since then has been a rewrite to suit versions...

so we've all stole from someone at the root of it all...

**Comment by Gomez** [comment]
Can this be used or help?
New in kodi 18:
https://github.com/xbmc/xbmc/pull/14125

**Comment by sinopsysHK** [comment]
looks promising ! I give it a try right away...

**Comment by sinopsysHK** [comment]
> Can this be used or help?
> New in kodi 18:
> [xbmc/xbmc#14125](https://github.com/xbmc/xbmc/pull/14125)

I gave a try but actually it is similar to this image: it is relying on another rendering driver but still having a formal renderer behind the scene (offscreen) thus keeping consuming CPU for GUI management even if not displayd.

I made a patch to provide Leia the same kind of headless option than Krypton was having.
It has been rejected by Kodi team (the same way it might have happened with Krypton version in the past) so it may have to be maintain aside for people who still want to have a lean Kodi based library back-end instead of migrating to Emby (as myself).

**Comment by sinopsysHK** [comment]
> Hi @sinopsysHK
> 
> Long time I have maintain the headless patch , but because build time take longer and longer on docker hub , I have stop this and switch to xpra with the overhead of ram and cpu because interface is now fully render.
> Just before leia release when I see that I can't build as fast as needed I've consider switch to linuxserver.io image. Then I see they just take my work ( and donations ... ).
> So I've start trying another way with fake X server (xpra) and soundcard (pulseaudio).
> 
> that's why they no more provide headless patch and now provide xpra images.
> 
> https://github.com/Celedhrim/docker-kodi-server

Thank you @Celedhrim for your previous work that helped me a lot to implement Leia's one and let me think it should be feasible : #88 I'll close this issue if PR accepted here :)

**Comment by sparklyballs** [comment]
@Celedhrim , @sinopsysHK 

PR #90 that will close this out when merged, gives specific credit for patches, past and present, and explicitly acknowledges that this project would not have been possible without them.

**Comment by Celedhrim** [comment]
:+1:  :)
